### ISSUE TITLE
[Suggestion] better World Map view

### ISSUE THREAD

**Issue by ffuentesm** [MehVahdJukaar/mapatlases-neoforge#34]
Would be possible to have the world map be a rectangle, like if you were opening a book? 
The current square view is a bit limiting and small for the game screen, it feels like looking at the minimap. 
![image](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/249d32d0-f0b4-4071-9f46-82a33a943070)

Could you have it be similar to Antique Atlas visualization? Just the extra space of seeing two pages instead of a single one would facilitate a lot during the experience. 
![635593944559692128](https://github.com/MehVahdJukaar/mapatlases-neoforge/assets/44974827/14917cb2-656e-46e6-a9e5-fa7c5dec4d18)

**Comment by MehVahdJukaar** [comment]
you can scale the gui up via config

**Comment by MehVahdJukaar** [comment]
also al guis are the same exact pixel perfect scale, scaling up is ery unconventional and non trivial to do actualy so that image down there is deceiving. Thats more or less as big as i see it on my screen , 1080p with the game guiscale set to 4. we tried havin it book view but the map unlike antique snt transparent so the middle section ends up looing weird as the line in between pages cant be slown and it would be just a big horizontal map rectange. might give it a second shot just so it can utilize a bit of the horizontal space aswell but the space to be gained isnt that big taking the scaling config into account

**Comment by ffuentesm** [comment]
Thanks, the open book map view helps a lot. 
Now the only weird this is that dragging that is not Consistent. If I move the cursor 1inch, the map moves 2 inches.

**Comment by MehVahdJukaar** [comment]
Yeah when zoomed in its a bit wonky I need to improve the math

**Comment by MehVahdJukaar** [comment]
also fixed
